server:
  error:
    include-stacktrace: on-param
    
spring:
  datasource:
    #url: jdbc:mysql://localhost:3306/anime?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    #Dá no mesmo
    url: jdbc:mysql://localhost:3306/anime?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
# Ou showsql ou login level debug      
#    show-sql: true

# Só roda em modo debug    
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG     